# Generated by Django 5.2.4 on 2025-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='appstore_url',
        ),
        migrations.AddField(
            model_name='project',
            name='playstore_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
