# Generated by Django 5.2.4 on 2025-07-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_url_project_appstore_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thumbail',
            new_name='thumbnail',
        ),
    ]
